name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      solution-file-path: KerbalVR_Mod/KerbalVR_Mod.sln
      use-ckan: true
